In [1]:
import requests

In [2]:
URL = "https://stephen-king-api.onrender.com/api/books"

res = requests.get(URL)

In [3]:
res

In [4]:
print(res.status_code)

200

In [5]:
print(res.text)

{"data":[{"id":1,"Year":1974,"Title":"Carrie","handle":"carrie","Publisher":"Doubleday","ISBN":"978-0-385-08695-0","Pages":199,"Notes":[""],"created_at":"2023-11-13T23:48:47.848Z","villains":[{"name":"Tina Blake","url":"https://stephen-king-api.onrender.com/api/villain/4"},{"name":"Cindi","url":"https://stephen-king-api.onrender.com/api/villain/14"},{"name":"Myra Crewes","url":"https://stephen-king-api.onrender.com/api/villain/16"},{"name":"Billy deLois","url":"https://stephen-king-api.onrender.com/api/villain/25"},{"name":"Kenny Garson","url":"https://stephen-king-api.onrender.com/api/villain/38"},{"name":"Mary Lila Grace","url":"https://stephen-king-api.onrender.com/api/villain/44"},{"name":"Christine Hargensen","url":"https://stephen-king-api.onrender.com/api/villain/49"},{"name":"Vic Mooney","url":"https://stephen-king-api.onrender.com/api/villain/75"},{"name":"The Mortimer Snerds","url":"https://stephen-king-api.onrender.com/api/villain/77"},{"name":"Billy Nolan","url":"https://stephen-king-api.onrender.com/api/villain/80"},{"name":"Elenor Richmond","url":"https://stephen-king-api.onrender.com/api/villain/90"},{"name":"Rachel Spies","url":"https://stephen-king-api.onrender.com/api/villain/94"},{"name":"Jackie Talbot","url":"https://stephen-king-api.onrender.com/api/villain/99"},{"name":"Donna and Mary Lila Grace Thibodeau","url":"https://stephen-king-api.onrender.com/api/villain/102"},{"name":"Jessica Upshaw","url":"https://stephen-king-api.onrender.com/api/villain/108"},{"name":"Norma Watson","url":"https://stephen-king-api.onrender.com/api/villain/109"},{"name":"Margaret White","url":"https://stephen-king-api.onrender.com/api/villain/113"}]},{"id":2,"Year":1975,"Title":"Salem's Lot","handle":"salem-s-lot","Publisher":"Doubleday","ISBN":"978-0-385-00751-1","Pages":439,"Notes":["Nominee, World Fantasy Award, 1976[2]"],"created_at":"2023-11-13T23:48:48.098Z","villains":[{"name":"Kurt Barlow","url":"https://stephen-king-api.onrender.com/api/villain/2"},{"name":"Richard Straker","url":"https://stephen-king-api.onrender.com/api/villain/98"}]},{"id":3,"Year":1977,"Title":"The Shining","handle":"the-shining","Publisher":"Doubleday","ISBN":"978-0-385-12167-5","Pages":447,"Notes":["Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]"],"created_at":"2023-11-13T23:48:48.219Z","villains":[{"name":"Horace M. Derwent","url":"https://stephen-king-api.onrender.com/api/villain/26"},{"name":"Delbert Grady","url":"https://stephen-king-api.onrender.com/api/villain/45"},{"name":"Jack Torrance","url":"https://stephen-king-api.onrender.com/api/villain/106"}]},{"id":4,"Year":1977,"Title":"Rage","handle":"rage","Publisher":"Signet Books","ISBN":"978-0-451-07645-8","Pages":211,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:48.339Z","villains":[]},{"id":5,"Year":1978,"Title":"The Stand","handle":"the-stand","Publisher":"Doubleday","ISBN":"978-0-385-12168-2","Pages":823,"Notes":["Nominee, World Fantasy Award, 1979","Runner-up (15th place), Locus Award, 1979[2]"],"created_at":"2023-11-13T23:48:48.477Z","villains":[{"name":"Donald Merwin Elbert","url":"https://stephen-king-api.onrender.com/api/villain/34"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"Lloyd Henreid","url":"https://stephen-king-api.onrender.com/api/villain/51"},{"name":"The Kid","url":"https://stephen-king-api.onrender.com/api/villain/62"},{"name":"Harold Lauder","url":"https://stephen-king-api.onrender.com/api/villain/64"},{"name":"Rat Man","url":"https://stephen-king-api.onrender.com/api/villain/87"}]},{"id":6,"Year":1979,"Title":"The Long Walk","handle":"the-long-walk","Publisher":"Signet Books","ISBN":"978-0-451-08754-6","Pages":384,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:48.608Z","villains":[{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"The Major","url":"https://stephen-king-api.onrender.com/api/villain/70"}]},{"id":7,"Year":1979,"Title":"The Dead Zone","handle":"the-dead-zone","Publisher":"Viking Press","ISBN":"978-0-670-26077-5","Pages":428,"Notes":["Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]"],"created_at":"2023-11-13T23:48:48.753Z","villains":[{"name":"Frank Dodd","url":"https://stephen-king-api.onrender.com/api/villain/29"},{"name":"Henrietta Dodd","url":"https://stephen-king-api.onrender.com/api/villain/30"},{"name":"Malcolm Janus","url":"https://stephen-king-api.onrender.com/api/villain/71"},{"name":"Sonny Elliman","url":"https://stephen-king-api.onrender.com/api/villain/93"},{"name":"Greg Stillson","url":"https://stephen-king-api.onrender.com/api/villain/97"},{"name":"The Devil's Dozen","url":"https://stephen-king-api.onrender.com/api/villain/100"}]},{"id":8,"Year":1980,"Title":"Firestarter","handle":"firestarter","Publisher":"Viking Press","ISBN":"978-0-670-31541-3","Pages":426,"Notes":["Nominee, British Fantasy Award’s August Derleth Award, 1981","Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]"],"created_at":"2023-11-13T23:48:48.876Z","villains":[{"name":"James Hollister","url":"https://stephen-king-api.onrender.com/api/villain/54"},{"name":"Charlie McGee","url":"https://stephen-king-api.onrender.com/api/villain/73"},{"name":"John Rainbird","url":"https://stephen-king-api.onrender.com/api/villain/86"}]},{"id":9,"Year":1981,"Title":"Roadwork","handle":"roadwork","Publisher":"Signet Books","ISBN":"978-0-451-09668-5","Pages":274,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:49.005Z","villains":[]},{"id":10,"Year":1981,"Title":"Cujo","handle":"cujo","Publisher":"Viking Press","ISBN":"978-0-670-45193-7","Pages":319,"Notes":["Winner, British Fantasy Award’s August Derleth Award, 1982","Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]"],"created_at":"2023-11-13T23:48:49.131Z","villains":[{"name":"Cujo","url":"https://stephen-king-api.onrender.com/api/villain/19"}]},{"id":11,"Year":1982,"Title":"The Running Man","handle":"the-running-man","Publisher":"Signet Books","ISBN":"978-0-451-11508-9","Pages":219,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:49.252Z","villains":[{"name":"The Gladiators","url":"https://stephen-king-api.onrender.com/api/villain/42"},{"name":"Damon Killian","url":"https://stephen-king-api.onrender.com/api/villain/63"}]},{"id":12,"Year":1982,"Title":"The Dark Tower: The Gunslinger","handle":"the-dark-tower-the-gunslinger","Publisher":"Grant","ISBN":"978-0-937986-50-9","Pages":224,"Notes":[""],"created_at":"2023-11-13T23:48:49.374Z","villains":[{"name":"Marten Broadcloak","url":"https://stephen-king-api.onrender.com/api/villain/10"},{"name":"Crimson King","url":"https://stephen-king-api.onrender.com/api/villain/17"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"Sylvia Pittston","url":"https://stephen-king-api.onrender.com/api/villain/84"}]},{"id":13,"Year":1983,"Title":"Christine","handle":"christine","Publisher":"Viking","ISBN":"978-0-670-22026-7","Pages":526,"Notes":["Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]"],"created_at":"2023-11-13T23:48:49.505Z","villains":[{"name":"Christine (car)","url":"https://stephen-king-api.onrender.com/api/villain/11"},{"name":"Arnie Cunningham","url":"https://stephen-king-api.onrender.com/api/villain/20"}]},{"id":14,"Year":1983,"Title":"Pet Sematary","handle":"pet-sematary","Publisher":"Doubleday","ISBN":"978-0-385-18244-7","Pages":374,"Notes":["Nominee, World Fantasy Award, 1984","Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]"],"created_at":"2023-11-13T23:48:49.637Z","villains":[{"name":"Winston Church","url":"https://stephen-king-api.onrender.com/api/villain/13"},{"name":"Gage Creed","url":"https://stephen-king-api.onrender.com/api/villain/15"},{"name":"Victor Pascow","url":"https://stephen-king-api.onrender.com/api/villain/83"},{"name":"Wendigo","url":"https://stephen-king-api.onrender.com/api/villain/110"}]},{"id":15,"Year":1983,"Title":"Cycle of the Werewolf","handle":"cycle-of-the-werewolf","Publisher":"Land of Enchantment","ISBN":"978-0-960-38282-8","Pages":127,"Notes":["Illustrated by Bernie Wrightson"],"created_at":"2023-11-13T23:48:49.757Z","villains":[{"name":"Lester Lowe","url":"https://stephen-king-api.onrender.com/api/villain/68"}]},{"id":16,"Year":1984,"Title":"The Talisman","handle":"the-talisman","Publisher":"Viking","ISBN":"978-0-670-69199-9","Pages":646,"Notes":["Written with Peter Straub","Nominee, World Fantasy Award, 1985","Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]"],"created_at":"2023-11-13T23:48:49.872Z","villains":[]},{"id":17,"Year":1984,"Title":"The Eyes of the Dragon","handle":"the-eyes-of-the-dragon","Publisher":"Philtrum Press (1984)Viking (1987)","ISBN":"978-0-670-81458-9","Pages":326,"Notes":["First published as a limited edition in 1984, then for the mass market in 1987"],"created_at":"2023-11-13T23:48:49.988Z","villains":[{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"}]},{"id":18,"Year":1984,"Title":"Thinner","handle":"thinner","Publisher":"NAL","ISBN":"978-0-453-00468-8","Pages":309,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:50.102Z","villains":[]},{"id":19,"Year":1986,"Title":"It","handle":"it","Publisher":"Viking","ISBN":"978-0-670-81302-5","Pages":1138,"Notes":["Winner, British Fantasy Award’s August Derleth Award, 1987","Nominee, World Fantasy Award, 1987","Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]"],"created_at":"2023-11-13T23:48:50.223Z","villains":[{"name":"Henry Bowers","url":"https://stephen-king-api.onrender.com/api/villain/7"},{"name":"Butch Bowers","url":"https://stephen-king-api.onrender.com/api/villain/8"},{"name":"Greta Bowie","url":"https://stephen-king-api.onrender.com/api/villain/9"},{"name":"Victor Criss","url":"https://stephen-king-api.onrender.com/api/villain/18"},{"name":"Marcia Fadden","url":"https://stephen-king-api.onrender.com/api/villain/35"},{"name":"John Garton","url":"https://stephen-king-api.onrender.com/api/villain/39"},{"name":"Peter Gordon","url":"https://stephen-king-api.onrender.com/api/villain/43"},{"name":"Patrick Hockstetter","url":"https://stephen-king-api.onrender.com/api/villain/53"},{"name":"Belch Huggins","url":"https://stephen-king-api.onrender.com/api/villain/55"},{"name":"It (Creature)","url":"https://stephen-king-api.onrender.com/api/villain/57"},{"name":"Richard P. Macklin","url":"https://stephen-king-api.onrender.com/api/villain/69"},{"name":"Alvin Marsh","url":"https://stephen-king-api.onrender.com/api/villain/72"},{"name":"Sally Mueller","url":"https://stephen-king-api.onrender.com/api/villain/79"},{"name":"Tom Rogan","url":"https://stephen-king-api.onrender.com/api/villain/91"},{"name":"Christopher Unwin","url":"https://stephen-king-api.onrender.com/api/villain/107"}]},{"id":20,"Year":1987,"Title":"The Dark Tower II: The Drawing of the Three","handle":"the-dark-tower-ii-the-drawing-of-the-three","Publisher":"Grant","ISBN":"978-0-937986-90-5","Pages":400,"Notes":["Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]"],"created_at":"2023-11-13T23:48:50.339Z","villains":[{"name":"Jack Mort","url":"https://stephen-king-api.onrender.com/api/villain/76"}]},{"id":21,"Year":1987,"Title":"Misery","handle":"misery","Publisher":"Viking","ISBN":"978-0-670-81364-3","Pages":310,"Notes":["Winner, Bram Stoker Award, 1988","Nominee, World Fantasy Award, 1988[2]"],"created_at":"2023-11-13T23:48:50.459Z","villains":[{"name":"Annie Wilkes","url":"https://stephen-king-api.onrender.com/api/villain/114"}]},{"id":22,"Year":1987,"Title":"The Tommyknockers","handle":"the-tommyknockers","Publisher":"Putnam","ISBN":"978-0-399-13314-5","Pages":558,"Notes":["Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]"],"created_at":"2023-11-13T23:48:50.579Z","villains":[{"name":"Tommyknockers","url":"https://stephen-king-api.onrender.com/api/villain/104"}]},{"id":23,"Year":1989,"Title":"The Dark Half","handle":"the-dark-half","Publisher":"Viking","ISBN":"978-0-670-82982-8","Pages":431,"Notes":["Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]"],"created_at":"2023-11-13T23:48:50.696Z","villains":[{"name":"George Stark","url":"https://stephen-king-api.onrender.com/api/villain/96"}]},{"id":24,"Year":1990,"Title":"The Stand Uncut","handle":"the-stand-uncut","Publisher":"Doubleday","ISBN":"978-0-385-19957-5","Pages":1152,"Notes":["The Complete & Uncut Edition","Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],"created_at":"2023-11-13T23:48:50.809Z","villains":[]},{"id":25,"Year":1991,"Title":"The Dark Tower III: The Waste Lands","handle":"the-dark-tower-iii-the-waste-lands","Publisher":"Grant","ISBN":"978-0-937986-17-2","Pages":512,"Notes":["Nominee, Bram Stoker Award, 1992","Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]"],"created_at":"2023-11-13T23:48:50.926Z","villains":[{"name":"Blaine the Mono","url":"https://stephen-king-api.onrender.com/api/villain/3"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"}]},{"id":26,"Year":1991,"Title":"Needful Things","handle":"needful-things","Publisher":"Viking","ISBN":"978-0-670-83953-7","Pages":690,"Notes":["Nominee, Bram Stoker Award, 1992","Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]"],"created_at":"2023-11-13T23:48:51.044Z","villains":[{"name":"Leland Gaunt","url":"https://stephen-king-api.onrender.com/api/villain/40"}]},{"id":27,"Year":1992,"Title":"Gerald's Game","handle":"gerald-s-game","Publisher":"Viking","ISBN":"978-0-670-84650-4","Pages":352,"Notes":[],"created_at":"2023-11-13T23:48:51.165Z","villains":[{"name":"Gerald Burlingame","url":"https://stephen-king-api.onrender.com/api/villain/41"},{"name":"Raymond Andrew Joubert","url":"https://stephen-king-api.onrender.com/api/villain/61"},{"name":"Tom Mahout","url":"https://stephen-king-api.onrender.com/api/villain/103"}]},{"id":28,"Year":1992,"Title":"Dolores Claiborne","handle":"dolores-claiborne","Publisher":"Viking","ISBN":"978-0-670-84452-4","Pages":305,"Notes":["Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]"],"created_at":"2023-11-13T23:48:51.295Z","villains":[{"name":"Joe St. George","url":"https://stephen-king-api.onrender.com/api/villain/95"}]},{"id":29,"Year":1994,"Title":"Insomnia","handle":"insomnia","Publisher":"Viking","ISBN":"978-0-670-85503-2","Pages":787,"Notes":["Nominee, Bram Stoker Award, 1995","Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]"],"created_at":"2023-11-13T23:48:51.415Z","villains":[{"name":"Crimson King","url":"https://stephen-king-api.onrender.com/api/villain/17"},{"name":"Susan Day","url":"https://stephen-king-api.onrender.com/api/villain/23"}]},{"id":30,"Year":1995,"Title":"Rose Madder","handle":"rose-madder","Publisher":"Viking","ISBN":"978-0-670-85869-9","Pages":420,"Notes":["Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]"],"created_at":"2023-11-13T23:48:51.533Z","villains":[{"name":"Norman Daniels","url":"https://stephen-king-api.onrender.com/api/villain/22"},{"name":"Susan Day","url":"https://stephen-king-api.onrender.com/api/villain/23"}]},{"id":31,"Year":1996,"Title":"The Green Mile","handle":"the-green-mile","Publisher":"Signet Books","ISBN":"978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4","Pages":400,"Notes":["Winner, Bram Stoker Award, 1997","Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]"],"created_at":"2023-11-13T23:48:51.660Z","villains":[{"name":"Percy Wetmore","url":"https://stephen-king-api.onrender.com/api/villain/111"},{"name":"William Wharton","url":"https://stephen-king-api.onrender.com/api/villain/112"}]},{"id":32,"Year":1996,"Title":"Desperation","handle":"desperation","Publisher":"Viking","ISBN":"978-0-670-86836-0","Pages":704,"Notes":["Twin novel of The Regulators","Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]"],"created_at":"2023-11-13T23:48:51.784Z","villains":[]},{"id":33,"Year":1996,"Title":"The Regulators","handle":"the-regulators","Publisher":"Dutton","ISBN":"978-0-525-94190-3","Pages":480,"Notes":["Published under pseudonym Richard Bachman","Twin novel of Desperation"],"created_at":"2023-11-13T23:48:51.900Z","villains":[]},{"id":34,"Year":1997,"Title":"The Dark Tower IV: Wizard and Glass","handle":"the-dark-tower-iv-wizard-and-glass","Publisher":"Grant","ISBN":"978-1-880418-38-3","Pages":787,"Notes":["Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998","Runner-up (6th place), Locus Award for Best Art Book, 1998[2]"],"created_at":"2023-11-13T23:48:52.019Z","villains":[{"name":"Blaine the Mono","url":"https://stephen-king-api.onrender.com/api/villain/3"},{"name":"Cordelia Delgado","url":"https://stephen-king-api.onrender.com/api/villain/24"},{"name":"Rhea Dubativo","url":"https://stephen-king-api.onrender.com/api/villain/32"},{"name":"John Farson","url":"https://stephen-king-api.onrender.com/api/villain/36"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"Eldred Jonas","url":"https://stephen-king-api.onrender.com/api/villain/60"}]},{"id":35,"Year":1998,"Title":"Bag of Bones","handle":"bag-of-bones","Publisher":"Scribner","ISBN":"978-0-684-85350-5","Pages":529,"Notes":["Winner, Bram Stoker Award, 1999","Winner, British Fantasy Award’s August Derleth Award, 1999","Winner, Locus Award for Best Dark Fantasy/Horror Novel, 1999[2]"],"created_at":"2023-11-13T23:48:52.137Z","villains":[]},{"id":36,"Year":1999,"Title":"The Girl Who Loved Tom Gordon","handle":"the-girl-who-loved-tom-gordon","Publisher":"Scribner","ISBN":"978-0-684-86762-5","Pages":224,"Notes":[],"created_at":"2023-11-13T23:48:52.251Z","villains":[]},{"id":37,"Year":2001,"Title":"Dreamcatcher","handle":"dreamcatcher","Publisher":"Scribner","ISBN":"978-0-743-21138-3","Pages":620,"Notes":[],"created_at":"2023-11-13T23:48:52.368Z","villains":[]},{"id":38,"Year":2001,"Title":"Black House","handle":"black-house","Publisher":"Random House","ISBN":"978-0-375-50439-6","Pages":625,"Notes":["Sequel to The Talisman","Written with Peter Straub","Nominee, Bram Stoker Award, 2002","Runner-up (7th place), Locus Award for Best Fantasy Novel, 2002[2]"],"created_at":"2023-11-13T23:48:52.483Z","villains":[{"name":"Crimson King","url":"https://stephen-king-api.onrender.com/api/villain/17"}]},{"id":39,"Year":2002,"Title":"From a Buick 8","handle":"from-a-buick-8","Publisher":"Scribner","ISBN":"978-0-743-21137-6","Pages":368,"Notes":["Nominee, Bram Stoker Award, 2003"],"created_at":"2023-11-13T23:48:52.604Z","villains":[{"name":"Brian Lippy","url":"https://stephen-king-api.onrender.com/api/villain/66"}]},{"id":40,"Year":2003,"Title":"The Dark Tower V: Wolves of the Calla","handle":"the-dark-tower-v-wolves-of-the-calla","Publisher":"Grant","ISBN":"978-1-880-41856-7","Pages":714,"Notes":["Nominee, Bram Stoker Award, 2004","Runner-up (4th place), Locus Award for Best Fantasy Novel, 2004[2]"],"created_at":"2023-11-13T23:48:52.735Z","villains":[]},{"id":41,"Year":2004,"Title":"The Dark Tower VI: Song of Susannah","handle":"the-dark-tower-vi-song-of-susannah","Publisher":"Grant","ISBN":"978-1-880-41859-8","Pages":432,"Notes":["Runner-up (4th place), Locus Award for Best Fantasy Novel, 2005"],"created_at":"2023-11-13T23:48:52.856Z","villains":[]},{"id":42,"Year":2004,"Title":"The Dark Tower VII: The Dark Tower","handle":"the-dark-tower-vii-the-dark-tower","Publisher":"978-1-880-41862-8","ISBN":"Grant","Pages":845,"Notes":["Winner, British Fantasy Award's August Derleth Award, 2005","Nominee, Bram Stoker Award, 2005[2]"],"created_at":"2023-11-13T23:48:53.001Z","villains":[{"name":"

In [6]:
print(res.content)

b'{"data":[{"id":1,"Year":1974,"Title":"Carrie","handle":"carrie","Publisher":"Doubleday","ISBN":"978-0-385-08695-0","Pages":199,"Notes":[""],"created_at":"2023-11-13T23:48:47.848Z","villains":[{"name":"Tina Blake","url":"https://stephen-king-api.onrender.com/api/villain/4"},{"name":"Cindi","url":"https://stephen-king-api.onrender.com/api/villain/14"},{"name":"Myra Crewes","url":"https://stephen-king-api.onrender.com/api/villain/16"},{"name":"Billy deLois","url":"https://stephen-king-api.onrender.com/api/villain/25"},{"name":"Kenny Garson","url":"https://stephen-king-api.onrender.com/api/villain/38"},{"name":"Mary Lila Grace","url":"https://stephen-king-api.onrender.com/api/villain/44"},{"name":"Christine Hargensen","url":"https://stephen-king-api.onrender.com/api/villain/49"},{"name":"Vic Mooney","url":"https://stephen-king-api.onrender.com/api/villain/75"},{"name":"The Mortimer Snerds","url":"https://stephen-king-api.onrender.com/api/villain/77"},{"name":"Billy Nolan","url":"https://stephen-king-api.onrender.com/api/villain/80"},{"name":"Elenor Richmond","url":"https://stephen-king-api.onrender.com/api/villain/90"},{"name":"Rachel Spies","url":"https://stephen-king-api.onrender.com/api/villain/94"},{"name":"Jackie Talbot","url":"https://stephen-king-api.onrender.com/api/villain/99"},{"name":"Donna and Mary Lila Grace Thibodeau","url":"https://stephen-king-api.onrender.com/api/villain/102"},{"name":"Jessica Upshaw","url":"https://stephen-king-api.onrender.com/api/villain/108"},{"name":"Norma Watson","url":"https://stephen-king-api.onrender.com/api/villain/109"},{"name":"Margaret White","url":"https://stephen-king-api.onrender.com/api/villain/113"}]},{"id":2,"Year":1975,"Title":"Salem\'s Lot","handle":"salem-s-lot","Publisher":"Doubleday","ISBN":"978-0-385-00751-1","Pages":439,"Notes":["Nominee, World Fantasy Award, 1976[2]"],"created_at":"2023-11-13T23:48:48.098Z","villains":[{"name":"Kurt Barlow","url":"https://stephen-king-api.onrender.com/api/villain/2"},{"name":"Richard Straker","url":"https://stephen-king-api.onrender.com/api/villain/98"}]},{"id":3,"Year":1977,"Title":"The Shining","handle":"the-shining","Publisher":"Doubleday","ISBN":"978-0-385-12167-5","Pages":447,"Notes":["Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]"],"created_at":"2023-11-13T23:48:48.219Z","villains":[{"name":"Horace M. Derwent","url":"https://stephen-king-api.onrender.com/api/villain/26"},{"name":"Delbert Grady","url":"https://stephen-king-api.onrender.com/api/villain/45"},{"name":"Jack Torrance","url":"https://stephen-king-api.onrender.com/api/villain/106"}]},{"id":4,"Year":1977,"Title":"Rage","handle":"rage","Publisher":"Signet Books","ISBN":"978-0-451-07645-8","Pages":211,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:48.339Z","villains":[]},{"id":5,"Year":1978,"Title":"The Stand","handle":"the-stand","Publisher":"Doubleday","ISBN":"978-0-385-12168-2","Pages":823,"Notes":["Nominee, World Fantasy Award, 1979","Runner-up (15th place), Locus Award, 1979[2]"],"created_at":"2023-11-13T23:48:48.477Z","villains":[{"name":"Donald Merwin Elbert","url":"https://stephen-king-api.onrender.com/api/villain/34"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"Lloyd Henreid","url":"https://stephen-king-api.onrender.com/api/villain/51"},{"name":"The Kid","url":"https://stephen-king-api.onrender.com/api/villain/62"},{"name":"Harold Lauder","url":"https://stephen-king-api.onrender.com/api/villain/64"},{"name":"Rat Man","url":"https://stephen-king-api.onrender.com/api/villain/87"}]},{"id":6,"Year":1979,"Title":"The Long Walk","handle":"the-long-walk","Publisher":"Signet Books","ISBN":"978-0-451-08754-6","Pages":384,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:48.608Z","villains":[{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"The Major","url":"https://stephen-king-api.onrender.com/api/villain/70"}]},{"id":7,"Year":1979,"Title":"The Dead Zone","handle":"the-dead-zone","Publisher":"Viking Press","ISBN":"978-0-670-26077-5","Pages":428,"Notes":["Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]"],"created_at":"2023-11-13T23:48:48.753Z","villains":[{"name":"Frank Dodd","url":"https://stephen-king-api.onrender.com/api/villain/29"},{"name":"Henrietta Dodd","url":"https://stephen-king-api.onrender.com/api/villain/30"},{"name":"Malcolm Janus","url":"https://stephen-king-api.onrender.com/api/villain/71"},{"name":"Sonny Elliman","url":"https://stephen-king-api.onrender.com/api/villain/93"},{"name":"Greg Stillson","url":"https://stephen-king-api.onrender.com/api/villain/97"},{"name":"The Devil\'s Dozen","url":"https://stephen-king-api.onrender.com/api/villain/100"}]},{"id":8,"Year":1980,"Title":"Firestarter","handle":"firestarter","Publisher":"Viking Press","ISBN":"978-0-670-31541-3","Pages":426,"Notes":["Nominee, British Fantasy Award\xe2\x80\x99s August Derleth Award, 1981","Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]"],"created_at":"2023-11-13T23:48:48.876Z","villains":[{"name":"James Hollister","url":"https://stephen-king-api.onrender.com/api/villain/54"},{"name":"Charlie McGee","url":"https://stephen-king-api.onrender.com/api/villain/73"},{"name":"John Rainbird","url":"https://stephen-king-api.onrender.com/api/villain/86"}]},{"id":9,"Year":1981,"Title":"Roadwork","handle":"roadwork","Publisher":"Signet Books","ISBN":"978-0-451-09668-5","Pages":274,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:49.005Z","villains":[]},{"id":10,"Year":1981,"Title":"Cujo","handle":"cujo","Publisher":"Viking Press","ISBN":"978-0-670-45193-7","Pages":319,"Notes":["Winner, British Fantasy Award\xe2\x80\x99s August Derleth Award, 1982","Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]"],"created_at":"2023-11-13T23:48:49.131Z","villains":[{"name":"Cujo","url":"https://stephen-king-api.onrender.com/api/villain/19"}]},{"id":11,"Year":1982,"Title":"The Running Man","handle":"the-running-man","Publisher":"Signet Books","ISBN":"978-0-451-11508-9","Pages":219,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:49.252Z","villains":[{"name":"The Gladiators","url":"https://stephen-king-api.onrender.com/api/villain/42"},{"name":"Damon Killian","url":"https://stephen-king-api.onrender.com/api/villain/63"}]},{"id":12,"Year":1982,"Title":"The Dark Tower: The Gunslinger","handle":"the-dark-tower-the-gunslinger","Publisher":"Grant","ISBN":"978-0-937986-50-9","Pages":224,"Notes":[""],"created_at":"2023-11-13T23:48:49.374Z","villains":[{"name":"Marten Broadcloak","url":"https://stephen-king-api.onrender.com/api/villain/10"},{"name":"Crimson King","url":"https://stephen-king-api.onrender.com/api/villain/17"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"Sylvia Pittston","url":"https://stephen-king-api.onrender.com/api/villain/84"}]},{"id":13,"Year":1983,"Title":"Christine","handle":"christine","Publisher":"Viking","ISBN":"978-0-670-22026-7","Pages":526,"Notes":["Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]"],"created_at":"2023-11-13T23:48:49.505Z","villains":[{"name":"Christine (car)","url":"https://stephen-king-api.onrender.com/api/villain/11"},{"name":"Arnie Cunningham","url":"https://stephen-king-api.onrender.com/api/villain/20"}]},{"id":14,"Year":1983,"Title":"Pet Sematary","handle":"pet-sematary","Publisher":"Doubleday","ISBN":"978-0-385-18244-7","Pages":374,"Notes":["Nominee, World Fantasy Award, 1984","Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]"],"created_at":"2023-11-13T23:48:49.637Z","villains":[{"name":"Winston Church","url":"https://stephen-king-api.onrender.com/api/villain/13"},{"name":"Gage Creed","url":"https://stephen-king-api.onrender.com/api/villain/15"},{"name":"Victor Pascow","url":"https://stephen-king-api.onrender.com/api/villain/83"},{"name":"Wendigo","url":"https://stephen-king-api.onrender.com/api/villain/110"}]},{"id":15,"Year":1983,"Title":"Cycle of the Werewolf","handle":"cycle-of-the-werewolf","Publisher":"Land of Enchantment","ISBN":"978-0-960-38282-8","Pages":127,"Notes":["Illustrated by Bernie Wrightson"],"created_at":"2023-11-13T23:48:49.757Z","villains":[{"name":"Lester Lowe","url":"https://stephen-king-api.onrender.com/api/villain/68"}]},{"id":16,"Year":1984,"Title":"The Talisman","handle":"the-talisman","Publisher":"Viking","ISBN":"978-0-670-69199-9","Pages":646,"Notes":["Written with Peter Straub","Nominee, World Fantasy Award, 1985","Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]"],"created_at":"2023-11-13T23:48:49.872Z","villains":[]},{"id":17,"Year":1984,"Title":"The Eyes of the Dragon","handle":"the-eyes-of-the-dragon","Publisher":"Philtrum Press (1984)Viking (1987)","ISBN":"978-0-670-81458-9","Pages":326,"Notes":["First published as a limited edition in 1984, then for the mass market in 1987"],"created_at":"2023-11-13T23:48:49.988Z","villains":[{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"}]},{"id":18,"Year":1984,"Title":"Thinner","handle":"thinner","Publisher":"NAL","ISBN":"978-0-453-00468-8","Pages":309,"Notes":["Published under pseudonym Richard Bachman"],"created_at":"2023-11-13T23:48:50.102Z","villains":[]},{"id":19,"Year":1986,"Title":"It","handle":"it","Publisher":"Viking","ISBN":"978-0-670-81302-5","Pages":1138,"Notes":["Winner, British Fantasy Award\xe2\x80\x99s August Derleth Award, 1987","Nominee, World Fantasy Award, 1987","Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]"],"created_at":"2023-11-13T23:48:50.223Z","villains":[{"name":"Henry Bowers","url":"https://stephen-king-api.onrender.com/api/villain/7"},{"name":"Butch Bowers","url":"https://stephen-king-api.onrender.com/api/villain/8"},{"name":"Greta Bowie","url":"https://stephen-king-api.onrender.com/api/villain/9"},{"name":"Victor Criss","url":"https://stephen-king-api.onrender.com/api/villain/18"},{"name":"Marcia Fadden","url":"https://stephen-king-api.onrender.com/api/villain/35"},{"name":"John Garton","url":"https://stephen-king-api.onrender.com/api/villain/39"},{"name":"Peter Gordon","url":"https://stephen-king-api.onrender.com/api/villain/43"},{"name":"Patrick Hockstetter","url":"https://stephen-king-api.onrender.com/api/villain/53"},{"name":"Belch Huggins","url":"https://stephen-king-api.onrender.com/api/villain/55"},{"name":"It (Creature)","url":"https://stephen-king-api.onrender.com/api/villain/57"},{"name":"Richard P. Macklin","url":"https://stephen-king-api.onrender.com/api/villain/69"},{"name":"Alvin Marsh","url":"https://stephen-king-api.onrender.com/api/villain/72"},{"name":"Sally Mueller","url":"https://stephen-king-api.onrender.com/api/villain/79"},{"name":"Tom Rogan","url":"https://stephen-king-api.onrender.com/api/villain/91"},{"name":"Christopher Unwin","url":"https://stephen-king-api.onrender.com/api/villain/107"}]},{"id":20,"Year":1987,"Title":"The Dark Tower II: The Drawing of the Three","handle":"the-dark-tower-ii-the-drawing-of-the-three","Publisher":"Grant","ISBN":"978-0-937986-90-5","Pages":400,"Notes":["Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]"],"created_at":"2023-11-13T23:48:50.339Z","villains":[{"name":"Jack Mort","url":"https://stephen-king-api.onrender.com/api/villain/76"}]},{"id":21,"Year":1987,"Title":"Misery","handle":"misery","Publisher":"Viking","ISBN":"978-0-670-81364-3","Pages":310,"Notes":["Winner, Bram Stoker Award, 1988","Nominee, World Fantasy Award, 1988[2]"],"created_at":"2023-11-13T23:48:50.459Z","villains":[{"name":"Annie Wilkes","url":"https://stephen-king-api.onrender.com/api/villain/114"}]},{"id":22,"Year":1987,"Title":"The Tommyknockers","handle":"the-tommyknockers","Publisher":"Putnam","ISBN":"978-0-399-13314-5","Pages":558,"Notes":["Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]"],"created_at":"2023-11-13T23:48:50.579Z","villains":[{"name":"Tommyknockers","url":"https://stephen-king-api.onrender.com/api/villain/104"}]},{"id":23,"Year":1989,"Title":"The Dark Half","handle":"the-dark-half","Publisher":"Viking","ISBN":"978-0-670-82982-8","Pages":431,"Notes":["Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]"],"created_at":"2023-11-13T23:48:50.696Z","villains":[{"name":"George Stark","url":"https://stephen-king-api.onrender.com/api/villain/96"}]},{"id":24,"Year":1990,"Title":"The Stand Uncut","handle":"the-stand-uncut","Publisher":"Doubleday","ISBN":"978-0-385-19957-5","Pages":1152,"Notes":["The Complete & Uncut Edition","Runner-up (2nd place), Locus Award\'s Best Horror/Dark Fantasy Novel, 1991[2]"],"created_at":"2023-11-13T23:48:50.809Z","villains":[]},{"id":25,"Year":1991,"Title":"The Dark Tower III: The Waste Lands","handle":"the-dark-tower-iii-the-waste-lands","Publisher":"Grant","ISBN":"978-0-937986-17-2","Pages":512,"Notes":["Nominee, Bram Stoker Award, 1992","Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]"],"created_at":"2023-11-13T23:48:50.926Z","villains":[{"name":"Blaine the Mono","url":"https://stephen-king-api.onrender.com/api/villain/3"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"}]},{"id":26,"Year":1991,"Title":"Needful Things","handle":"needful-things","Publisher":"Viking","ISBN":"978-0-670-83953-7","Pages":690,"Notes":["Nominee, Bram Stoker Award, 1992","Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]"],"created_at":"2023-11-13T23:48:51.044Z","villains":[{"name":"Leland Gaunt","url":"https://stephen-king-api.onrender.com/api/villain/40"}]},{"id":27,"Year":1992,"Title":"Gerald\'s Game","handle":"gerald-s-game","Publisher":"Viking","ISBN":"978-0-670-84650-4","Pages":352,"Notes":[],"created_at":"2023-11-13T23:48:51.165Z","villains":[{"name":"Gerald Burlingame","url":"https://stephen-king-api.onrender.com/api/villain/41"},{"name":"Raymond Andrew Joubert","url":"https://stephen-king-api.onrender.com/api/villain/61"},{"name":"Tom Mahout","url":"https://stephen-king-api.onrender.com/api/villain/103"}]},{"id":28,"Year":1992,"Title":"Dolores Claiborne","handle":"dolores-claiborne","Publisher":"Viking","ISBN":"978-0-670-84452-4","Pages":305,"Notes":["Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]"],"created_at":"2023-11-13T23:48:51.295Z","villains":[{"name":"Joe St. George","url":"https://stephen-king-api.onrender.com/api/villain/95"}]},{"id":29,"Year":1994,"Title":"Insomnia","handle":"insomnia","Publisher":"Viking","ISBN":"978-0-670-85503-2","Pages":787,"Notes":["Nominee, Bram Stoker Award, 1995","Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]"],"created_at":"2023-11-13T23:48:51.415Z","villains":[{"name":"Crimson King","url":"https://stephen-king-api.onrender.com/api/villain/17"},{"name":"Susan Day","url":"https://stephen-king-api.onrender.com/api/villain/23"}]},{"id":30,"Year":1995,"Title":"Rose Madder","handle":"rose-madder","Publisher":"Viking","ISBN":"978-0-670-85869-9","Pages":420,"Notes":["Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]"],"created_at":"2023-11-13T23:48:51.533Z","villains":[{"name":"Norman Daniels","url":"https://stephen-king-api.onrender.com/api/villain/22"},{"name":"Susan Day","url":"https://stephen-king-api.onrender.com/api/villain/23"}]},{"id":31,"Year":1996,"Title":"The Green Mile","handle":"the-green-mile","Publisher":"Signet Books","ISBN":"978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4","Pages":400,"Notes":["Winner, Bram Stoker Award, 1997","Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]"],"created_at":"2023-11-13T23:48:51.660Z","villains":[{"name":"Percy Wetmore","url":"https://stephen-king-api.onrender.com/api/villain/111"},{"name":"William Wharton","url":"https://stephen-king-api.onrender.com/api/villain/112"}]},{"id":32,"Year":1996,"Title":"Desperation","handle":"desperation","Publisher":"Viking","ISBN":"978-0-670-86836-0","Pages":704,"Notes":["Twin novel of The Regulators","Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]"],"created_at":"2023-11-13T23:48:51.784Z","villains":[]},{"id":33,"Year":1996,"Title":"The Regulators","handle":"the-regulators","Publisher":"Dutton","ISBN":"978-0-525-94190-3","Pages":480,"Notes":["Published under pseudonym Richard Bachman","Twin novel of Desperation"],"created_at":"2023-11-13T23:48:51.900Z","villains":[]},{"id":34,"Year":1997,"Title":"The Dark Tower IV: Wizard and Glass","handle":"the-dark-tower-iv-wizard-and-glass","Publisher":"Grant","ISBN":"978-1-880418-38-3","Pages":787,"Notes":["Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998","Runner-up (6th place), Locus Award for Best Art Book, 1998[2]"],"created_at":"2023-11-13T23:48:52.019Z","villains":[{"name":"Blaine the Mono","url":"https://stephen-king-api.onrender.com/api/villain/3"},{"name":"Cordelia Delgado","url":"https://stephen-king-api.onrender.com/api/villain/24"},{"name":"Rhea Dubativo","url":"https://stephen-king-api.onrender.com/api/villain/32"},{"name":"John Farson","url":"https://stephen-king-api.onrender.com/api/villain/36"},{"name":"Randall Flagg","url":"https://stephen-king-api.onrender.com/api/villain/37"},{"name":"Eldred Jonas","url":"https://stephen-king-api.onrender.com/api/villain/60"}]},{"id":35,"Year":1998,"Title":"Bag of Bones","handle":"bag-of-bones","Publisher":"Scribner","ISBN":"978-0-684-85350-5","Pages":529,"Notes":["Winner, Bram Stoker Award, 1999","Winner, British Fantasy Award\xe2\x80\x99s August Derleth Award, 1999","Winner, Locus Award for Best Dark Fantasy/Horror Novel, 1999[2]"],"created_at":"2023-11-13T23:48:52.137Z","villains":[]},{"id":36,"Year":1999,"Title":"The Girl Who Loved Tom Gordon","handle":"the-girl-who-loved-tom-gordon","Publisher":"Scribner","ISBN":"978-0-684-86762-5","Pages":224,"Notes":[],"created_at":"2023-11-13T23:48:52.251Z","villains":[]},{"id":37,"Year":2001,"Title":"Dreamcatcher","handle":"dreamcatcher","Publisher":"Scribner","ISBN":"978-0-743-21138-3","Pages":620,"Notes":[],"created_at":"2023-11-13T23:48:52.368Z","villains":[]},{"id":38,"Year":2001,"Title":"Black House","handle":"black-house","Publisher":"Random House","ISBN":"978-0-375-50439-6","Pages":625,"Notes":["Sequel to The Talisman","Written with Peter Straub","Nominee, Bram Stoker Award, 2002","Runner-up (7th place), Locus Award for Best Fantasy Novel, 2002[2]"],"created_at":"2023-11-13T23:48:52.483Z","villains":[{"name":"Crimson King","url":"https://stephen-king-api.onrender.com/api/villain/17"}]},{"id":39,"Year":2002,"Title":"From a Buick 8","handle":"from-a-buick-8","Publisher":"Scribner","ISBN":"978-0-743-21137-6","Pages":368,"Notes":["Nominee, Bram Stoker Award, 2003"],"created_at":"2023-11-13T23:48:52.604Z","villains":[{"name":"Brian Lippy","url":"https://stephen-king-api.onrender.com/api/villain/66"}]},{"id":40,"Year":2003,"Title":"The Dark Tower V: Wolves of the Calla","handle":"the-dark-tower-v-wolves-of-the-calla","Publisher":"Grant","ISBN":"978-1-880-41856-7","Pages":714,"Notes":["Nominee, Bram Stoker Award, 2004","Runner-up (4th place), Locus Award for Best Fantasy Novel, 2004[2]"],"created_at":"2023-11-13T23:48:52.735Z","villains":[]},{"id":41,"Year":2004,"Title":"The Dark Tower VI: Song of Susannah","handle":"the-dark-tower-vi-song-of-susannah","Publisher":"Grant","ISBN":"978-1-880-41859-8","Pages":432,"Notes":["Runner-up (4th place), Locus Award for Best Fantasy Novel, 2005"],"created_at":"2023-11-13T23:48:52.856Z","villains":[]},{"id":42,"Year":2004,"Title":"The Dark Tower VII: The Dark Tower","handle":"the-dark-tower-vii-the-dark-tower","Publisher":"978-1-880-41862-8","ISBN":"Grant","Pages":845,"Notes":["Winner, British Fantasy Award\'s August Derleth Award, 2005","Nominee, Bram Stoker Award, 2005[2]"],"created_a

In [7]:
print(res.headers)

{'Date': 'Fri, 29 May 2026 15:23:54 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'cf-cache-status': 'DYNAMIC', 'etag': 'W/"696f-W8etsExFqAJgjLqJa20LIWLl3iI"', 'rndr-id': '7211da79-ae98-4e17', 'Server': 'cloudflare', 'vary': 'Accept-Encoding', 'x-powered-by': 'Express', 'x-render-origin-server': 'Render', 'Content-Encoding': 'gzip', 'CF-RAY': 'a03680b9e92944f0-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [8]:
json_data = res.json()
json_data

{'data': [{'id': 1,
   'Year': 1974,
   'Title': 'Carrie',
   'handle': 'carrie',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-08695-0',
   'Pages': 199,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:47.848Z',
   'villains': [{'name': 'Tina Blake',
     'url': 'https://stephen-king-api.onrender.com/api/villain/4'},
    {'name': 'Cindi',
     'url': 'https://stephen-king-api.onrender.com/api/villain/14'},
    {'name': 'Myra Crewes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/16'},
    {'name': 'Billy deLois',
     'url': 'https://stephen-king-api.onrender.com/api/villain/25'},
    {'name': 'Kenny Garson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/38'},
    {'name': 'Mary Lila Grace',
     'url': 'https://stephen-king-api.onrender.com/api/villain/44'},
    {'name': 'Christine Hargensen',
     'url': 'https://stephen-king-api.onrender.com/api/villain/49'},
    {'name': 'Vic Mooney',
     'url': 'https://stephen-king-api.onrender.com/api/villain/75'},
    {'name': 'The Mortimer Snerds',
     'url': 'https://stephen-king-api.onrender.com/api/villain/77'},
    {'name': 'Billy Nolan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/80'},
    {'name': 'Elenor Richmond',
     'url': 'https://stephen-king-api.onrender.com/api/villain/90'},
    {'name': 'Rachel Spies',
     'url': 'https://stephen-king-api.onrender.com/api/villain/94'},
    {'name': 'Jackie Talbot',
     'url': 'https://stephen-king-api.onrender.com/api/villain/99'},
    {'name': 'Donna and Mary Lila Grace Thibodeau',
     'url': 'https://stephen-king-api.onrender.com/api/villain/102'},
    {'name': 'Jessica Upshaw',
     'url': 'https://stephen-king-api.onrender.com/api/villain/108'},
    {'name': 'Norma Watson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/109'},
    {'name': 'Margaret White',
     'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]},
  {'id': 2,
   'Year': 1975,
   'Title': "Salem's Lot",
   'handle': 'salem-s-lot',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-00751-1',
   'Pages': 439,
   'Notes': ['Nominee, World Fantasy Award, 1976[2]'],
   'created_at': '2023-11-13T23:48:48.098Z',
   'villains': [{'name': 'Kurt Barlow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/2'},
    {'name': 'Richard Straker',
     'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]},
  {'id': 3,
   'Year': 1977,
   'Title': 'The Shining',
   'handle': 'the-shining',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12167-5',
   'Pages': 447,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'],
   'created_at': '2023-11-13T23:48:48.219Z',
   'villains': [{'name': 'Horace M. Derwent',
     'url': 'https://stephen-king-api.onrender.com/api/villain/26'},
    {'name': 'Delbert Grady',
     'url': 'https://stephen-king-api.onrender.com/api/villain/45'},
    {'name': 'Jack Torrance',
     'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]},
  {'id': 4,
   'Year': 1977,
   'Title': 'Rage',
   'handle': 'rage',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-07645-8',
   'Pages': 211,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.339Z',
   'villains': []},
  {'id': 5,
   'Year': 1978,
   'Title': 'The Stand',
   'handle': 'the-stand',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12168-2',
   'Pages': 823,
   'Notes': ['Nominee, World Fantasy Award, 1979',
    'Runner-up (15th place), Locus Award, 1979[2]'],
   'created_at': '2023-11-13T23:48:48.477Z',
   'villains': [{'name': 'Donald Merwin Elbert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/34'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Lloyd Henreid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/51'},
    {'name': 'The Kid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/62'},
    {'name': 'Harold Lauder',
     'url': 'https://stephen-king-api.onrender.com/api/villain/64'},
    {'name': 'Rat Man',
     'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]},
  {'id': 6,
   'Year': 1979,
   'Title': 'The Long Walk',
   'handle': 'the-long-walk',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-08754-6',
   'Pages': 384,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.608Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'The Major',
     'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]},
  {'id': 7,
   'Year': 1979,
   'Title': 'The Dead Zone',
   'handle': 'the-dead-zone',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-26077-5',
   'Pages': 428,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'],
   'created_at': '2023-11-13T23:48:48.753Z',
   'villains': [{'name': 'Frank Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/29'},
    {'name': 'Henrietta Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/30'},
    {'name': 'Malcolm Janus',
     'url': 'https://stephen-king-api.onrender.com/api/villain/71'},
    {'name': 'Sonny Elliman',
     'url': 'https://stephen-king-api.onrender.com/api/villain/93'},
    {'name': 'Greg Stillson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/97'},
    {'name': "The Devil's Dozen",
     'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]},
  {'id': 8,
   'Year': 1980,
   'Title': 'Firestarter',
   'handle': 'firestarter',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-31541-3',
   'Pages': 426,
   'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981',
    'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'],
   'created_at': '2023-11-13T23:48:48.876Z',
   'villains': [{'name': 'James Hollister',
     'url': 'https://stephen-king-api.onrender.com/api/villain/54'},
    {'name': 'Charlie McGee',
     'url': 'https://stephen-king-api.onrender.com/api/villain/73'},
    {'name': 'John Rainbird',
     'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]},
  {'id': 9,
   'Year': 1981,
   'Title': 'Roadwork',
   'handle': 'roadwork',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-09668-5',
   'Pages': 274,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.005Z',
   'villains': []},
  {'id': 10,
   'Year': 1981,
   'Title': 'Cujo',
   'handle': 'cujo',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-45193-7',
   'Pages': 319,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982',
    'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'],
   'created_at': '2023-11-13T23:48:49.131Z',
   'villains': [{'name': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]},
  {'id': 11,
   'Year': 1982,
   'Title': 'The Running Man',
   'handle': 'the-running-man',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-11508-9',
   'Pages': 219,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.252Z',
   'villains': [{'name': 'The Gladiators',
     'url': 'https://stephen-king-api.onrender.com/api/villain/42'},
    {'name': 'Damon Killian',
     'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]},
  {'id': 12,
   'Year': 1982,
   'Title': 'The Dark Tower: The Gunslinger',
   'handle': 'the-dark-tower-the-gunslinger',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-50-9',
   'Pages': 224,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:49.374Z',
   'villains': [{'name': 'Marten Broadcloak',
     'url': 'https://stephen-king-api.onrender.com/api/villain/10'},
    {'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Sylvia Pittston',
     'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]},
  {'id': 13,
   'Year': 1983,
   'Title': 'Christine',
   'handle': 'christine',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-22026-7',
   'Pages': 526,
   'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.505Z',
   'villains': [{'name': 'Christine (car)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/11'},
    {'name': 'Arnie Cunningham',
     'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]},
  {'id': 14,
   'Year': 1983,
   'Title': 'Pet Sematary',
   'handle': 'pet-sematary',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-18244-7',
   'Pages': 374,
   'Notes': ['Nominee, World Fantasy Award, 1984',
    'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.637Z',
   'villains': [{'name': 'Winston Church',
     'url': 'https://stephen-king-api.onrender.com/api/villain/13'},
    {'name': 'Gage Creed',
     'url': 'https://stephen-king-api.onrender.com/api/villain/15'},
    {'name': 'Victor Pascow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/83'},
    {'name': 'Wendigo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]},
  {'id': 15,
   'Year': 1983,
   'Title': 'Cycle of the Werewolf',
   'handle': 'cycle-of-the-werewolf',
   'Publisher': 'Land of Enchantment',
   'ISBN': '978-0-960-38282-8',
   'Pages': 127,
   'Notes': ['Illustrated by Bernie Wrightson'],
   'created_at': '2023-11-13T23:48:49.757Z',
   'villains': [{'name': 'Lester Lowe',
     'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]},
  {'id': 16,
   'Year': 1984,
   'Title': 'The Talisman',
   'handle': 'the-talisman',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-69199-9',
   'Pages': 646,
   'Notes': ['Written with Peter Straub',
    'Nominee, World Fantasy Award, 1985',
    'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'],
   'created_at': '2023-11-13T23:48:49.872Z',
   'villains': []},
  {'id': 17,
   'Year': 1984,
   'Title': 'The Eyes of the Dragon',
   'handle': 'the-eyes-of-the-dragon',
   'Publisher': 'Philtrum Press (1984)Viking (1987)',
   'ISBN': '978-0-670-81458-9',
   'Pages': 326,
   'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'],
   'created_at': '2023-11-13T23:48:49.988Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 18,
   'Year': 1984,
   'Title': 'Thinner',
   'handle': 'thinner',
   'Publisher': 'NAL',
   'ISBN': '978-0-453-00468-8',
   'Pages': 309,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:50.102Z',
   'villains': []},
  {'id': 19,
   'Year': 1986,
   'Title': 'It',
   'handle': 'it',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81302-5',
   'Pages': 1138,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987',
    'Nominee, World Fantasy Award, 1987',
    'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'],
   'created_at': '2023-11-13T23:48:50.223Z',
   'villains': [{'name': 'Henry Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/7'},
    {'name': 'Butch Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/8'},
    {'name': 'Greta Bowie',
     'url': 'https://stephen-king-api.onrender.com/api/villain/9'},
    {'name': 'Victor Criss',
     'url': 'https://stephen-king-api.onrender.com/api/villain/18'},
    {'name': 'Marcia Fadden',
     'url': 'https://stephen-king-api.onrender.com/api/villain/35'},
    {'name': 'John Garton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/39'},
    {'name': 'Peter Gordon',
     'url': 'https://stephen-king-api.onrender.com/api/villain/43'},
    {'name': 'Patrick Hockstetter',
     'url': 'https://stephen-king-api.onrender.com/api/villain/53'},
    {'name': 'Belch Huggins',
     'url': 'https://stephen-king-api.onrender.com/api/villain/55'},
    {'name': 'It (Creature)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/57'},
    {'name': 'Richard P. Macklin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/69'},
    {'name': 'Alvin Marsh',
     'url': 'https://stephen-king-api.onrender.com/api/villain/72'},
    {'name': 'Sally Mueller',
     'url': 'https://stephen-king-api.onrender.com/api/villain/79'},
    {'name': 'Tom Rogan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/91'},
    {'name': 'Christopher Unwin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]},
  {'id': 20,
   'Year': 1987,
   'Title': 'The Dark Tower II: The Drawing of the Three',
   'handle': 'the-dark-tower-ii-the-drawing-of-the-three',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-90-5',
   'Pages': 400,
   'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.339Z',
   'villains': [{'name': 'Jack Mort',
     'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]},
  {'id': 21,
   'Year': 1987,
   'Title': 'Misery',
   'handle': 'misery',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81364-3',
   'Pages': 310,
   'Notes': ['Winner, Bram Stoker Award, 1988',
    'Nominee, World Fantasy Award, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.459Z',
   'villains': [{'name': 'Annie Wilkes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]},
  {'id': 22,
   'Year': 1987,
   'Title': 'The Tommyknockers',
   'handle': 'the-tommyknockers',
   'Publisher': 'Putnam',
   'ISBN': '978-0-399-13314-5',
   'Pages': 558,
   'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.579Z',
   'villains': [{'name': 'Tommyknockers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]},
  {'id': 23,
   'Year': 1989,
   'Title': 'The Dark Half',
   'handle': 'the-dark-half',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-82982-8',
   'Pages': 431,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'],
   'created_at': '2023-11-13T23:48:50.696Z',
   'villains': [{'name': 'George Stark',
     'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]},
  {'id': 24,
   'Year': 1990,
   'Title': 'The Stand Uncut',
   'handle': 'the-stand-uncut',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-19957-5',
   'Pages': 1152,
   'Notes': ['The Complete & Uncut Edition',
    "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],
   'created_at': '2023-11-13T23:48:50.809Z',
   'villains': []},
  {'id': 25,
   'Year': 1991,
   'Title': 'The Dark Tower III: The Waste Lands',
   'handle': 'the-dark-tower-iii-the-waste-lands',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-17-2',
   'Pages': 512,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:50.926Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 26,
   'Year': 1991,
   'Title': 'Needful Things',
   'handle': 'needful-things',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-83953-7',
   'Pages': 690,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:51.044Z',
   'villains': [{'name': 'Leland Gaunt',
     'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]},
  {'id': 27,
   'Year': 1992,
   'Title': "Gerald's Game",
   'handle': 'gerald-s-game',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84650-4',
   'Pages': 352,
   'Notes': [],
   'created_at': '2023-11-13T23:48:51.165Z',
   'villains': [{'name': 'Gerald Burlingame',
     'url': 'https://stephen-king-api.onrender.com/api/villain/41'},
    {'name': 'Raymond Andrew Joubert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/61'},
    {'name': 'Tom Mahout',
     'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]},
  {'id': 28,
   'Year': 1992,
   'Title': 'Dolores Claiborne',
   'handle': 'dolores-claiborne',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84452-4',
   'Pages': 305,
   'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'],
   'created_at': '2023-11-13T23:48:51.295Z',
   'villains': [{'name': 'Joe St. George',
     'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]},
  {'id': 29,
   'Year': 1994,
   'Title': 'Insomnia',
   'handle': 'insomnia',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85503-2',
   'Pages': 787,
   'Notes': ['Nominee, Bram Stoker Award, 1995',
    'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.415Z',
   'villains': [{'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 30,
   'Year': 1995,
   'Title': 'Rose Madder',
   'handle': 'rose-madder',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85869-9',
   'Pages': 420,
   'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.533Z',
   'villains': [{'name': 'Norman Daniels',
     'url': 'https://stephen-king-api.onrender.com/api/villain/22'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 31,
   'Year': 1996,
   'Title': 'The Green Mile',
   'handle': 'the-green-mile',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4',
   'Pages': 400,
   'Notes': ['Winner, Bram Stoker Award, 1997',
    'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.660Z',
   'villains': [{'name': 'Percy Wetmore',
     'url': 'https://stephen-king-api.onrender.com/api/villain/111'},
    {'name': 'William Wharton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]},
  {'id': 32,
   'Year': 1996,
   'Title': 'Desperation',
   'handle': 'desperation',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-86836-0',
   'Pages': 704,
   'Notes': ['Twin novel of The Regulators',
    'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.784Z',
   'villains': []},
  {'id': 33,
   'Year': 1996,
   'Title': 'The Regulators',
   'handle': 'the-regulators',
   'Publisher': 'Dutton',
   'ISBN': '978-0-525-94190-3',
   'Pages': 480,
   'Notes': ['Published under pseudonym Richard Bachman',
    'Twin novel of Desperation'],
   'created_at': '2023-11-13T23:48:51.900Z',
   'villains': []},
  {'id': 34,
   'Year': 1997,
   'Title': 'The Dark Tower IV: Wizard and Glass',
   'handle': 'the-dark-tower-iv-wizard-and-glass',
   'Publisher': 'Grant',
   'ISBN': '978-1-880418-38-3',
   'Pages': 787,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998',
    'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'],
   'created_at': '2023-11-13T23:48:52.019Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Cordelia Delgado',
     'url': 'https://stephen-king-api.onrender.com/api/villain/24'},
    {'name': 'Rhea Dubativo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/32'},

In [9]:
# Converting it into a pandas dataFrame
import pandas as pd

In [10]:
df = pd.json_normalize(json_data["data"])

In [11]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [12]:
df2 = df.copy()
df2

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [13]:
df2 = df2[["id", "Title", "Publisher", "ISBN", "Pages"]]
df2

    id          Title        Publisher               ISBN  Pages
0    1         Carrie        Doubleday  978-0-385-08695-0    199
1    2    Salem's Lot        Doubleday  978-0-385-00751-1    439
2    3    The Shining        Doubleday  978-0-385-12167-5    447
3    4           Rage     Signet Books  978-0-451-07645-8    211
4    5      The Stand        Doubleday  978-0-385-12168-2    823
..  ..            ...              ...                ...    ...
58  59   The Outsider         Scribner  978-1-50118-098-9    576
59  60      Elevation         Scribner  978-1-98210-231-9    144
60  61  The Institute         Scribner  978-1-98211-056-7    576
61  62          Later  Hard Case Crime  978-1-78909-649-1    256
62  63  Billy Summers         Scribner  978-1-982-17361-6    528

[63 rows x 5 columns]

In [14]:
link = "https://dattebayo-api.onrender.com/characters"

req = requests.get(link)

In [15]:
info_data = req.json()
info_data

{'characters': [{'id': 1344,
   'name': 'Naruto Uzumaki',
   'images': ['https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_Part_I.png',
    'https://static.wikia.nocookie.net/naruto/images/7/7d/Naruto_Part_II.png'],
   'debut': {'manga': 'Naruto Chapter #1',
    'anime': 'Naruto Episode #1',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Find the Four-Leaf Red Clover!',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Minato Namikaze',
    'mother': 'Kushina Uzumaki',
    'son': 'Boruto Uzumaki',
    'daughter': 'Himawari Uzumaki',
    'wife': 'Hinata Uzumaki',
    'adoptive son': 'Kawaki',
    'godfather': 'Jiraiya'},
   'jutsu': ['All Directions Shuriken',
    'Baryon Mode',
    'Big Ball Rasengan',
    'Big Ball Rasenshuriken',
    'Big Ball Spiralling Serial Zone Spheres',
    'Boil Release: Unrivalled Strength',
    'Chakra Transfer Technique',
    'Clone Body Blow',
    'Clone Flying Arrow',
    'Clone Spinning Heel Drop (Anime only)',
    'Combination Transformation',
    'Continuous Tailed Beast Balls',
    'Crescent Moon Rasengan',
    'Earth Release: Earth-Style Wall',
    'Erupting Propulsion Fist',
    'Fire Release: Toad Oil Flame Bullet (Anime only)',
    'Frog Kata',
    'Frog Strike',
    'Gelel Rasengan',
    'Gentle Step Spiralling Twin Lion Fists',
    'Guts Rasengan',
    'Harem Technique',
    'Hurricane Thunderclap — Majestic Attire Sword Stroke',
    'Ink Creation',
    'Kurama Arm Attack',
    'Mini-Rasenshuriken',
    'Multiple Shadow Clone Technique',
    'Naruto Region Combo',
    'Naruto Uzumaki Combo',
    'Naruto Uzumaki Two Thousand Combo',
    "Naruto and Shion's Super Chakra Rasengan",
    'Negative Emotions Sensing',
    'New Sexy Technique',
    'Nine-Tails Chakra Mode',
    'Ninja Art: Bare-Handed Blade Block',
    'One Thousand Years of Death',
    'Pachinko Technique (Anime only)',
    'Parachute',
    'Parent and Child Rasengan',
    'Planetary Rasengan',
    'Rasengan',
    'Rasengan: Flash',
    'Regeneration Ability',
    'Runt Ball Rasengan (Anime only)',
    'Sage Art: Lava Release Rasenshuriken',
    'Sage Art: Magnet Release Rasengan',
    'Sage Art: Many Ultra-Big Ball Spiralling Serial Spheres',
    'Sage Art: Super Tailed Beast Rasenshuriken',
    'Sage Mode',
    'Scorch Release: Halo Hurricane Jet Black Arrow Style Zero',
    'Seven-Coloured Rasengan',
    'Sexy Reverse Harem Technique',
    'Sexy Technique',
    'Sexy Technique: Pole Dance and Nice Body (Anime only)',
    'Shadow Clone Technique',
    'Shadow Shuriken Technique',
    'Shuriken Shadow Clone Technique (Anime only)',
    'Six Paths Sage Mode',
    'Six Paths Senjutsu',
    'Six Paths Yang Power',
    'Six Paths — Chibaku Tensei',
    'Six Paths: Ultra-Big Ball Rasenshuriken',
    'Soap Bubble Ninjutsu (Anime only)',
    'Spiralling Absorption Sphere',
    'Spiralling Serial Spheres',
    'Spiralling Strife Spheres',
    'Strong Fist (Anime only)',
    'Summoning Technique (Toad)',
    'Summoning: Food Cart Destroyer Technique',
    'Super Mini-Tailed Beast Ball',
    'Super-Ultra-Big Ball Rasengan',
    'Supreme Ultimate Rasengan',
    'Tailed Beast Ball',
    'Tailed Beast Ball Rasenshuriken',
    'Tailed Beast Chakra Arms',
    'Tailed Beast Full Charge',
    'Tailed Beast Rasengan',
    'Tailed Beast Shockwave',
    'Torii Seal',
    'Tornado Rasengan',
    'Truth-Seeking Ball',
    'Turning into a Frog Technique (Anime only)',
    'Typhoon Water Vortex Technique',
    'Ultra-Big Ball Rasengan',
    'Ultra-Many Spiralling Serial Spheres',
    'Uzumaki Formation (Anime only)',
    'Wind Release: Rasengan',
    'Wind Release: Rasenshuriken',
    'Wind Release: Repeated Rasenshuriken',
    'Wind Release: Toad Gun (Anime only)',
    'Wind Release: Toad Oil Bullet (Anime only)',
    'Wind Release: Toad Oil Flame Bullet (Anime only)',
    'Wind Release: Ultra-Big Ball Rasenshuriken',
    'Wisdom Wolf Decay'],
   'natureType': ['Wind Release  (Affinity)',
    'Lightning Release',
    'Earth Release',
    'Water Release',
    'Fire Release',
    'Lava Release',
    'Magnet Release',
    'Boil Release',
    'Yin Release',
    'Yang Release',
    'Yin–Yang Release'],
   'personal': {'birthdate': 'October 10',
    'sex': 'Male',
    'age': {'Part I': '12–13', 'Part II': '15–17', 'Academy Graduate': '12'},
    'height': {'Part I': '145.3cm - 147.5cm',
     'Part II': '166cm',
     'Blank Period': '180cm'},
    'weight': {'Part I': '40.1kg - 40.6kg', 'Part II': '50.9kg'},
    'bloodType': 'B',
    'kekkeiGenkai': ['Lava Release', 'Magnet Release', 'Boil Release'],
    'classification': ['Jinchūriki', 'Sage', 'Sensor Type'],
    'tailedBeast': 'Shukaku, Matatabi, Isobu, Son Gokū, Kokuō, Saiken, Chōmei, Gyūki, Kurama (Forms)',
    'occupation': ['Hokage', 'Chūnin Exams Proctor  (Anime only)'],
    'affiliation': ['Konohagakure', 'Mount Myōboku', 'Allied Shinobi Forces'],
    'team': ['Team Kakashi',
     'Sasuke Recovery Team',
     'Konoha 11  (Anime only)',
     'Bikōchū Search Team  (Anime only)',
     'Kaima Capture Team  (Anime only)',
     'Star Guard Team  (Anime only)',
     'Peddlers Escort Team  (Anime only)',
     'Kazekage Rescue Team',
     'Team One  (Anime only)',
     'Eight Man Squad',
     'Hanabi Rescue Team  (Movie only)'],
    'clan': 'Uzumaki',
    'titles': ['うずまきナルトUzumakiNaruto',
     'the-off,NumberOneUnpredictable,NoisyNinja(目立ちたがり屋で意外性no.1のドタバタ忍者,MedachitagariyaDeIgaiseiNanbāWanNoDotabataNinja,EnglishTv:NumberOneHyperactive,KnuckleheadNinja)',
     'childOfTheProphecy(予言の子,YogenNoKo)',
     'saviourOfThisWorld(この世の救世主,KonoYoNoKyūseishu)',
     'heroOfTheHiddenLeaf(木ノ葉隠れの英雄,KonohagakureNoEiyū,LiterallyMeaning:HeroOfTheHiddenTreeLeaves)',
     'boyOfMiracles(奇跡を起こす少年,KisekiOOkosuShōnen)',
     "konoha'sOrangeHokage(木ノ葉のオレンジ火影,KonohaNoOrenjiHokage,LiterallyMeaning:TreeLeaves'OrangeFireShadow)",
     'seventhHokage(七代目火影,NanadaimeHokage,LiterallyMeaning:SeventhFireShadow)',
     'fox(狐,Kitsune)']},
   'rank': {'ninjaRank': {'Part I': 'Genin', 'Gaiden': 'Kage'},
    'ninjaRegistration': '012607'},
   'tools': ['Absorbing Hand',
    'Bō (Anime only)',
    'Chakra Blade (Anime only)',
    'Flying Thunder God Kunai',
    'Fūma Shuriken',
    'Hidden Kunai Mechanism',
    'Konoha Chakra Blade',
    'Sand',
    'Stone of Gelel'],
   'voiceActors': {'japanese': ['Junko Takeuchi',
     'Ema Kogure   (Sexy Technique)'],
    'english': ['Maile Flanagan',
     'Stephanie Sheh   (Sexy Technique)',
     'Jeannie Elias   (Sexy Technique) (episode 53-55)',
     'Mary Elizabeth McGlynn   (Sexy Technique) (episode 177)',
     'Kate Higgins   (Sexy Technique) (episode 229)']}},
  {'id': 1307,
   'name': 'Sasuke Uchiha',
   'images': ['https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_1.png',
    'https://static.wikia.nocookie.net/naruto/images/1/13/Sasuke_Part_2.png'],
   'debut': {'manga': 'Naruto Chapter #3',
    'anime': 'Naruto Episode #1',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Find the Four-Leaf Red Clover!',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Fugaku Uchiha',
    'mother': 'Mikoto Uchiha',
    'brother': 'Itachi Uchiha',
    'daughter': 'Sarada Uchiha',
    'wife': 'Sakura Uchiha'},
   'jutsu': ['Afterglow',
    'Amaterasu',
    'Amaterasu: Flame Wrapping Fire',
    'Amenotejikara',
    'Animal Path',
    'Area Scanning Technique',
    'Asura Path',
    "Banshō Ten'in (Anime only)",
    'Binding Snake Glare Spell',
    'Blaze Release: Honoikazuchi (Anime only)',
    'Blaze Release: Kagutsuchi',
    'Blaze Release: Susanoo Kagutsuchi',
    'Blaze Release: Yasaka Magatama',
    'Chibaku Tensei',
    'Chidori',
    'Chidori Current',
    'Chidori Light Sword',
    'Chidori Senbon',
    'Chidori Sharp Spear',
    'Coercion Sharingan',
    'Combination Transformation (Anime only)',
    'Cursed Seal of Heaven',
    'Demonic Illusion: Mirage Crow',
    'Demonic Illusion: Shackling Stakes Technique',
    'Deva Path',
    'Earth Release: Stone Luster',
    'Evil Releasing Method',
    'Fire Release: Dragon Fire Technique',
    'Fire Release: Great Dragon Fire Technique',
    'Fire Release: Great Fireball Technique',
    'Fire Release: Phoenix Sage Fire Technique',
    'Genjutsu: Sharingan',
    'Hidden Shadow Snake Hands',
    'Human Path',
    'Hurricane Thunderclap — Majestic Attire Sword Stroke',
    "Indra's Arrow",
    'Kirin',
    'Lightning Flash',
    'Lion Combo',
    'Lorentz Gun (Novel only)',
    'Majestic Attire: Susanoo',
    'Manipulated Shuriken Technique',
    'Manipulating Windmill Triple Blades',
    'Moonlight',
    'Naka Shrine Pass Technique',
    'Naraka Path',
    'Orochimaru-Style Body Replacement Technique',
    'Outer Path',
    'Pachinko Technique (Anime only)',
    'Peregrine Falcon Drop',
    'Preta Path',
    'Reverse Summoning Technique',
    "Sasuke Uchiha's Space–Time Dōjutsu",
    'Scorch Release: Halo Hurricane Jet Black Arrow Style Zero',
    'Shadow Clone Technique',
    'Shadow Shuriken Technique',
    'Shadow of the Dancing Leaf',
    'Six Paths Technique',
    'Six Paths Yin Power',
    'Six Paths — Chibaku Tensei',
    'Strong Fist',
    'Summoning Technique (Hawk, Snake)',
    'Summoning: Lightning Flash Blade Creation',
    'Supercooled Water Technique',
    'Surging Fire Wild Dance',
    'Susanoo',
    'Susanoo: Captive Slash',
    'Susanoo: Chidori',
    'Susanoo: Crush',
    'Susanoo: Fist',
    'Susanoo: Great Fireball Technique (Anime only)',
    'Sword of Kagutsuchi',
    'Sword of Kusanagi: Chidori Katana',
    'Uchiha Style Shurikenjutsu: "Lightning": Triple',
    'Water Release: Water Formation Wall (Novel only)'],
   'natureType': ['Lightning Release  (Affinity; Anime only)',
    'Fire Release',
    'Wind Release',
    'Earth Release',
    'Water Release',
    'Yin Release'],
   'personal': {'birthdate': 'July 23',
    'sex': 'Male',
    'age': {'Part I': '12–13', 'Part II': '16–17', 'Academy Graduate': '12'},
    'height': {'Part I': '150.8cm - 153.2cm',
     'Part II': '168cm',
     'Blank Period': '182cm'},
    'weight': {'Part I': '42.2kg - 43.5kg', 'Part II': '52.2kg'},
    'bloodType': 'AB',
    'kekkeiGenkai': ['Sharingan', 'Eternal Mangekyō Sharingan', 'Rinnegan'],
    'classification': 'Missing-nin',
    'occupation': 'Head of the Uchiha Clan',
    'affiliation': ['Konohagakure', 'Otogakure', 'Ryūchi Cave', 'Akatsuki'],
    'team': ['Team Kakashi', 'Sound Four', 'Taka'],
    'clan': 'Uchiha',
    'titles': ['うちはサスケUchihaSasuke',
     'childOfTheProphecy(予言の子,YogenNoKo)',
     'sasukeOfTheSharingan(写輪眼のサスケ,SharinganNoSasuke)',
     'supportingKage(支う影,Sasaukage,LiterallyMeaning:SupportingShadow)']},
   'rank': {'ninjaRank': {'Part I': 'Genin'}, 'ninjaRegistration': '012606'},
   'tools': ['Bow & Arrow',
    'Fūma Shuriken',
    'Katar',
    'Kusari (Anime only)',
    'Mind Awakening Pill',
    'Scalpel (Anime only)',
    'Sword',
    'Sword of Kusanagi',
    'Wire Strings'],
   'voiceActors': {'japanese': ['Noriaki Sugiyama',
     'Nao Tōyama   (Infant and Child)'],
    'english': ['Yuri Lowenthal', 'Erica Mendez   (Infant)']}},
  {'id': 1299,
   'name': 'Madara Uchiha',
   'images': ['https://static.wikia.nocookie.net/naruto/images/f/fd/Madara.png'],
   'debut': {'manga': 'Naruto Chapter #370',
    'anime': 'Naruto Shippūden Episode #130',
    'novel': 'Kakashi Hiden: Lightning in the Icy Sky  (Mentioned)',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 2',
    'ova': 'Naruto Shippūden: UNSG anime cutscenes',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Tajima Uchiha', 'brother': 'Izuna Uchiha'},
   'jutsu': ['Animal Path',
    'Asura Path',
    'Black Receiver',
    'Blocking Technique Absorption Seal',
    'Chibaku Tensei',
    'Demonic Statue Chains',
    'Deva Path',
    'Evil Disturbance Waltz',
    'Fire Release: Dragon Flame Release Song Technique',
    'Fire Release: Great Fire Annihilation',
    'Fire Release: Great Fire Destruction',
    'Fire Release: Great Fireball Technique',
    'Fire Release: Great Flame Flower (Anime only)',
    'Fire Release: Hiding in Ash and Dust Technique',
    'Forbidden Individual Curse Tag',
    'Genjutsu: Sharingan',
    'God: Nativity of a World of Trees',
    'Gunbai Fanned Wind (Anime only)',
    'Hiding in Surface Technique',
    'Human Path',
    'Infinite Tsukuyomi',
    'Izanagi',
    'Kamui',
    'Limbo: Border Jail',
    'Majestic Attire: Susanoo',
    'Multiple Wood Release Clone Technique',
    'Naraka Path',
    'Outer Path',
    'Preta Path',
    'Regeneration Ability',
    'Sage Art: Storm Release Light Fang',
    'Sage Art: Yin Release Lightning Dispatch',
    'Sensing Technique',
    'Shadow Clone Technique',
    'Six Paths Senjutsu',
    'Six Paths Technique',
    'Six Paths Ten-Tails Coffin Seal',
    'Summoning Technique (Demonic Statue of the Outer Path, Kurama)',
    'Summoning: Demonic Statue of the Outer Path',
    'Susanoo',
    'Susanoo: Fist',
    'Tengai Shinsei',
    'Transcription Seal: Izanagi',
    'Truth-Seeking Ball',
    'Uchiha Return',
    'Will Materialisation',
    'Wood Clone Technique',
    'Wood Release Secret Technique: Nativity of a World of Trees',
    'Wood Release: Advent of a World of Flowering Trees',
    'Wood Release: Wood Dragon Technique',
    'Yasaka Magatama'],
   'natureType': ['Fire Release',
    'Wind Release',
    'Lightning Release',
    'Earth Release',
    'Water Release',
    'Wood Release',
    'Storm Release',
    'Yin Release',
    'Yang Release',
    'Yin–Yang Release'],
   'personal': {'birthdate': 'December 24',
    'sex': 'Male',
    'status': 'Deceased',
    'height': {'Part II': '179cm'},
    'weight': {'Part II': '71.3kg'},
    'bloodType': 'O',
    'kekkeiGenkai': ['Sharingan',
     'Eternal Mangekyō Sharingan',
     'Rinnegan',
     'Wood Release',
     'Storm Release'],
    'kekkeiMōra': 'Rinne Sharingan',
    'classification': ['Jinchūriki', 'Missing-nin', 'Sensor Type', 'Sage'],
    'tailedBeast': 'Ten-Tails (Forms)',
    'occupation': ['Co-founder of Konohagakure',
     'Head of the Uchiha clan  (Former)'],
    'affiliation': ['Konohagakure', 'Akatsuki'],
    'partner': ['Obito Uchiha', 'Black Zetsu'],
    'clan': 'Uchiha',
    'titles': ['うちはマダラUchihaMadara',
     'secondSixPaths(二人目の六道,FutarimeNoRikudō)',
     'saviourOfThisWorld(この世の救世主,KonoYoNoKyūseishu)',
     'ghostOfTheUchiha(うちはの亡霊,UchihaNoBōrei)']},
   'tools': ['Fūma Shuriken',
    'Gunbai',
    'Kama',
    'Spear (Anime only)',
    'Sword',
    'Tantō (Anime only)'],
   'uniqueTraits': ['Can absorb chakra'],
   'voiceActors': {'japanese': ['Naoya Uchida', 'Gō Inoue   (Child)'],
    'english': ['Neil Kaplan', 'Xander Mobus   (Child)']}},
  {'id': 376,
   'name': 'Kakashi Hatake',
   'images': ['https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png',
    'https://static.wikia.nocookie.net/naruto/images/2/25/Kakashi_Part_III.png'],
   'debut': {'manga': 'Naruto Chapter #3',
    'anime': 'Naruto Episode #3',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Find the Four-Leaf Red Clover!',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Sakumo Hatake'},
   'jutsu': ['Area Scanning Technique',
    'Chidori',
    'Demonic Illusion: Hell Viewing Technique',
    'Earth Release: Double Suicide Decapitation Technique',
    'Earth Release: Earth Wave Technique (Anime only)',
    'Earth Release: Earth-Style Wall',
    'Earth Release: Hiding Like a Mole Technique',
    'Earth Release: Multiple Earth-Style Wall (Anime only)',
    'Earth Release: Rending Drill Fang',
    'Eight Gates',
    'Evil Sealing Method',
    'Eye Mind Reading (Anime only)',
    'Fire Release: Great Fireball Technique (Anime only)',
    'Fire Release: Water Mist (Novel only)',
    'Flying Revolving Sword (Anime only)',
    'Front Lotus (Anime only)',
    'Genjutsu: Sharingan',
    'Ground Splitting Technique',
    'Hiding in Mist Technique (Anime only)',
    'Ice Release: One Horned White Whale',
    'Kamui',
    'Kamui Lightning Cutter',
    'Kamui Shuriken',
    'Lightning Cutter',
    'Lightning Release: Lightning Beast Tracking Fang',
    'Lightning Release: Purple Electricity',
    'Lightning Release: Shadow Clone Technique',
    'Lightning Transmission',
    'Multiple Shadow Clone Technique',
    'One Thousand Years of Death',
    'Peregrine Falcon Drop (Anime only)',
    'Rasengan',
    'Shadow Clone Technique',
    'Shadow of the Dancing Leaf (Anime only)',
    'Silent Killing',
    'Strong Fist (Anime only)',
    'Summoning Technique (Ninken)',
    'Summoning: Earth Release: Tracking Fang Technique',
    'Susanoo',
    'Water Clone Technique',
    'Water Release: Great Waterfall Technique',
    'Water Release: Water Beast',
    'Water Release: Water Bullet Technique',
    'Water Release: Water Dragon Bullet Technique',
    'Water Release: Water Formation Wall',
    'Water Release: Water Shark Bullet Technique',
    'White Light Blade'],
   'natureType': ['Lightning Release  (Affinity)',
    'Earth Release',
    'Water Release',
    'Fire Release',
    'Wind Release',
    'Yin Release',
    'Yang Release'],
   'personal': {'birthdate': 'September 15',
    'sex': 'Male',
    'age': {'Part I': '26–27',
     'Part II': '29–31',
     'Academy Graduate': '5',
     'Chunin Promotion': '6'},
    'height': {'Part I': '181cm'},
    'weight': {'Part I': '67.5kg'},
    'bloodType': 'O',
    'kekkeiGenkai': ['Sharingan', 'Mangekyō Sharingan'],
    'occupation': ['Anbu Captain  (Former)',
     'Third Division Commander of the Allied Shinobi Forces',
     'Hokage',
     'Genin Exams Proctor  (Anime only)'],
    'affiliation': ['Konohagakure',
     'Root  (Anime only)',
     'Allied Shinobi Forces'],
    'team': ['Team Minato',
     'Team Ro  (Anime only)',
     'Team Kakashi',
     'Kazekage Rescue Team',
     'Team Asuma  (Temporarily)',
     'Team One  (Anime only)',
     'Team 8  (Temporarily)',
     'Eight Man Squad',
     'Third Division'],
    'clan': 'Hatake',
    'titles': ['はたけカカシHatakeKakashi',
     'copyNinjaKakashi(コピー忍者のカカシ,KopīNinjaNoKakashi)',
     'kakashiOfTheSharingan(写輪眼のカカシ,SharinganNoKakashi,LiterallyMeaning:KakashiOfTheCopyWheelEye)',
     'heroOfTheSharingan(写輪眼の英雄,SharinganNoEiyū,LiterallyMeaning:HeroOfTheCopyWheelEye)',
     'cold-bloodedKakashi(冷血カカシ,ReiketsuKakashi)',
     'friend-killerKakashi(仲間殺しのカカシ,NakamagoroshiNoKakashi)',
     'sixthHokage(六代目火影,RokudaimeHokage,LiterallyMeaning:SixthFireShadow)',
     'sukea(スケア)']},
   'rank': {'ninjaRank': {'Part I': 'Jōnin', 'Blank Period': 'Kage'},
    'ninjaRegistration': '009720'},
   'tools': ['Bow & Arrow (Anime only)',
    'Chakra-Suppressing Seal',
    'Flying Thunder God Kunai',
    'Kubikiribōchō',
    'Kusarigama (Anime only)',
    'Lightning Barrel (Anime only)',
    'Makibishi',
    'Sword',
    'Tantō',
    'White Light Chakra Sabre',
    'Wire Strings'],
   'voiceActors': {'japanese': ['Kazuhiko Inoue',
     'Mutsumi Tamura  (Child)',
     'Kenichi Suzumura   (Sukea)'],
    'english': ['Dave Wittenberg', 'Xander Mobus   (Sukea)']}},
  {'id': 928,
   'name': 'Orochimaru',
   'images': ['https://static.wikia.nocookie.net/naruto/images/1/14/Orochimaru_Infobox.png',
    'https://static.wikia.nocookie.net/naruto/images/b/be/Orochimaru_Part_III.png'],
   'debut': {'manga': 'Naruto Chapter #45',
    'anime': 'Naruto Episode #27',
    'novel': 'Sasuke Shinden: Book of Sunrise',
    'movie': 'Naruto Shippūden the Movie: Bonds',
    'game': 'Naruto: Ninja Council',
    'ova': 'Hidden Leaf Village Grand Sports Festival!',

## New task

In [16]:
url = "https://www.scrapethissite.com/pages/simple/"

In [17]:
resp = requests.get(url)

In [18]:
print(resp.status_code)

200

In [19]:
print(resp.text)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [20]:
print(resp.content)

b'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            \xc3\x85land\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-

In [21]:
print(resp.headers)

{'Date': 'Fri, 29 May 2026 15:24:01 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=S2ZF6GJhxTYay0T4ZSBicfozmKx1n%2FB2e1e1aNOG%2Flk%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1780068241"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=S2ZF6GJhxTYay0T4ZSBicfozmKx1n%2FB2e1e1aNOG%2Flk%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1780068241"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'Cf-Cache-Status': 'DYNAMIC', 'Content-Encoding': 'gzip', 'CF-RAY': 'a03680ebc8d7c5da-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [22]:
# Downloading and storing to files

with open("Scrapped Data/data1.html", "w", encoding="utf-8") as f:
    f.write(resp.text)

In [23]:
# Using Beautiful Soup
from bs4 import BeautifulSoup

with open("Scrapped Data/data1.html", "r") as f:
    content = f.read()

soup = BeautifulSoup(content, "lxml")

In [24]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Ã…land
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint BarthÃ©lemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">BrasÃ­lia</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [25]:
soup.find("h1") # finding first h1 tag

<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>

In [26]:
soup.find("h3")

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [ ]:
# Can directly access them too
soup.h3

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [32]:
all_h3 = soup.find_all("h3") # all country names
print(type(all_h3))

<class 'bs4.element.ResultSet'>

In [33]:
for h3 in all_h3:
    print(h3)

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Ã…land
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint BarthÃ©lemy
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bw"></i>
                            Botswana
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-by"></i>
                            Belarus
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-bz"></i>
                            Belize
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ca"></i>
                            Canada
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cc"></i>
                            Cocos [Keeling] Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cd"></i>
                            Democratic Republic of the Congo
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cf"></i>
                            Central African Republic
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cg"></i>
                            Republic of the Congo
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ch"></i>
                            Switzerland
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ci"></i>
                            Ivory Coast
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ck"></i>
                            Cook Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cl"></i>
                            Chile
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cm"></i>
                            Cameroon
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cn"></i>
                            China
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-co"></i>
                            Colombia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cr"></i>
                            Costa Rica
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cu"></i>
                            Cuba
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cv"></i>
                            Cape Verde
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cw"></i>
                            Curacao
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cx"></i>
                            Christmas Island
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cy"></i>
                            Cyprus
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-cz"></i>
                            Czech Republic
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-de"></i>
                            Germany
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-dj"></i>
                            Djibouti
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-dk"></i>
                            Denmark
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-dm"></i>
                            Dominica
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-do"></i>
                            Dominican Republic
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-dz"></i>
                            Algeria
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ec"></i>
                            Ecuador
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ee"></i>
                            Estonia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-eg"></i>
                            Egypt
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-eh"></i>
                            Western Sahara
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-er"></i>
                            Eritrea
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-es"></i>
                            Spain
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-et"></i>
                            Ethiopia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-fi"></i>
                            Finland
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-fj"></i>
                            Fiji
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-fk"></i>
                            Falkland Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-fm"></i>
                            Micronesia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-fo"></i>
                            Faroe Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-fr"></i>
                            France
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ga"></i>
                            Gabon
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gb"></i>
                            United Kingdom
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gd"></i>
                            Grenada
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ge"></i>
                            Georgia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gf"></i>
                            French Guiana
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gg"></i>
                            Guernsey
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gh"></i>
                            Ghana
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gi"></i>
                            Gibraltar
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gl"></i>
                            Greenland
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gm"></i>
                            Gambia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gn"></i>
                            Guinea
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gp"></i>
                            Guadeloupe
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gq"></i>
                            Equatorial Guinea
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gr"></i>
                            Greece
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gs"></i>
                            South Georgia and the South Sandwich Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gt"></i>
                            Guatemala
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gu"></i>
                            Guam
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gw"></i>
                            Guinea-Bissau
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-gy"></i>
                            Guyana
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-hk"></i>
                            Hong Kong
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-hm"></i>
                            Heard Island and McDonald Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-hn"></i>
                            Honduras
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-hr"></i>
                            Croatia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ht"></i>
                            Haiti
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-hu"></i>
                            Hungary
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-id"></i>
                            Indonesia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ie"></i>
                            Ireland
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-il"></i>
                            Israel
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-im"></i>
                            Isle of Man
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-in"></i>
                            India
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-io"></i>
                            British Indian Ocean Territory
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-iq"></i>
                            Iraq
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ir"></i>
                            Iran
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-is"></i>
                            Iceland
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-it"></i>
                            Italy
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-je"></i>
                            Jersey
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-jm"></i>
                            Jamaica
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-jo"></i>
                            Jordan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-jp"></i>
                            Japan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ke"></i>
                            Kenya
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kg"></i>
                            Kyrgyzstan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kh"></i>
                            Cambodia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ki"></i>
                            Kiribati
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-km"></i>
                            Comoros
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kn"></i>
                            Saint Kitts and Nevis
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kp"></i>
                            North Korea
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kr"></i>
                            South Korea
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kw"></i>
                            Kuwait
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ky"></i>
                            Cayman Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-kz"></i>
                            Kazakhstan
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-la"></i>
                            Laos
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lb"></i>
                            Lebanon
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lc"></i>
                            Saint Lucia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-li"></i>
                            Liechtenstein
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lk"></i>
                            Sri Lanka
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lr"></i>
                            Liberia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ls"></i>
                            Lesotho
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lt"></i>
                            Lithuania
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lu"></i>
                            Luxembourg
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-lv"></i>
                            Latvia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ly"></i>
                            Libya
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ma"></i>
                            Morocco
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mc"></i>
                            Monaco
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-md"></i>
                            Moldova
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-me"></i>
                            Montenegro
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mf"></i>
                            Saint Martin
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mg"></i>
                            Madagascar
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mh"></i>
                            Marshall Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mk"></i>
                            Macedonia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ml"></i>
                            Mali
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mm"></i>
                            Myanmar [Burma]
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mn"></i>
                            Mongolia
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mo"></i>
                            Macao
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mp"></i>
                            Northern Mariana Islands
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-mq"></i>

In [ ]:
# A clean way 
for h3 in all_h3:
    name = h3.get_text(strip=True) # To get the text inside of it

In [ ]:
for h3 in all_h3:
    name = h3.get_text(strip=True)
    print(h3.find_parent("div")["class"]) # to find the parent element of it

['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']

In [46]:
for h3 in all_h3:
    name = h3.get_text(strip=True)
    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    print(h3.find_next("div").select_one("span.country-population").get_text(strip=True))
    # print(h3.attrs)

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [44]:
print(h3.attrs)

{'class': ['country-name']}

In [47]:
all_countries = []
for h3 in all_h3:
    name = h3.get_text(strip=True)
    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    print(h3.find_next("div").select_one("span.country-population").get_text(strip=True))

    all_countries.append([name, population])

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [48]:
all_countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Ã…land', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint BarthÃ©lemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['RÃ©union', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['SÃ£o TomÃ© and PrÃ\xadncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [49]:
import pandas as pd

In [53]:
df = pd.DataFrame(all_countries, columns=["Names", "Population"])
df

                    Names Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [54]:
df.head()

                  Names Population
0               Andorra      84000
1  United Arab Emirates    4975593
2           Afghanistan   29121286
3   Antigua and Barbuda      86754
4              Anguilla      13254

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Names       250 non-null    object
 1   Population  250 non-null    object
dtypes: object(2)
memory usage: 4.0+ KB

In [59]:
df.to_csv("country.csv", index=False)