## Pandas Introduction

In [1]:
import pandas as pd

In [ ]:
# An example of creating a Dataframe using a dictionary
info = {
    "Name:": ["John", "David", "Thomas"],
    "CGPA:": [8.9, 9.0, 9.2]
}

dataf = pd.DataFrame(info)
print(dataf)

    Name:  CGPA:
0    John    8.9
1   David    9.0
2  Thomas    9.2

In [ ]:
dataf

    Name:  CGPA:
0    John    8.9
1   David    9.0
2  Thomas    9.2

In [18]:
# Creating a series using a list
# Index and Labels are same by default
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

# Indexing
print(s[0])
print(s[2])
print(s[0:3]) # using slicing

# Creating custom labels
print("---------------------------------")
s1 = pd.Series([22, 25, 27, 29, 24], index=["John", "David", "Thomas", "Ross", "Kramer"])
print(s1)

# Indexing
print(s1["John"])
print(s1["Thomas"])
#print(s1[0]) # Can do this too, just get a warning not an error
#Generally we don't use custom labels and indexing together
print(s1.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3
0    1
1    2
2    3
dtype: int64
---------------------------------
John      22
David     25
Thomas    27
Ross      29
Kramer    24
dtype: int64
22
27
Index(['John', 'David', 'Thomas', 'Ross', 'Kramer'], dtype='object')

In [ ]:
# Series properties
s2 = pd.Series([1, 2, 3, 4, 5])
print(s2)

new_s2 = s2.drop(1)
print(s2)
print(new_s2)

#Other properties are same as in numPy arrays:

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
2    3
3    4
4    5
dtype: int64

In [27]:
# DataFrame in pandas
data = {
    "Name:": ["Thomas", "John", "Henry"],
    "Age:" : [24, 25, 27],
    "CGPA:" : [9.1, 8.9, 9.0]
}

df = pd.DataFrame(data)
print(df)
print(type(df))
print("-------------")
print(df.index)
print(df.columns)

    Name:  Age:  CGPA:
0  Thomas    24    9.1
1    John    25    8.9
2   Henry    27    9.0
<class 'pandas.core.frame.DataFrame'>
-------------
RangeIndex(start=0, stop=3, step=1)
Index(['Name:', 'Age:', 'CGPA:'], dtype='object')

In [24]:
df

    Name:  Age:  CGPA:
0  Thomas    24    9.1
1    John    25    8.9
2   Henry    27    9.0

In [31]:
# Creating dataFrame using list of lists
data1 = pd.DataFrame([["Adam", 22], ["Jack", 23], ["Tim", 25]], columns=["Name", "Age"])
print(data1)

   Name  Age
0  Adam   22
1  Jack   23
2   Tim   25

In [33]:
# Creating using numPy arrays
import numpy as np
num_arr = np.array([[1, 2, 3], [4, 5, 6]])

num_df = pd.DataFrame(num_arr, columns=["A", "B", "C" ])
print(num_df)

   A  B  C
0  1  2  3
1  4  5  6