## Pandas Introduction

In [1]:
import pandas as pd

In [ ]:
# An example of creating a Dataframe using a dictionary
info = {
    "Name:": ["John", "David", "Thomas"],
    "CGPA:": [8.9, 9.0, 9.2]
}

dataf = pd.DataFrame(info)
print(dataf)

    Name:  CGPA:
0    John    8.9
1   David    9.0
2  Thomas    9.2

In [ ]:
dataf

    Name:  CGPA:
0    John    8.9
1   David    9.0
2  Thomas    9.2

In [18]:
# Creating a series using a list
# Index and Labels are same by default
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

# Indexing
print(s[0])
print(s[2])
print(s[0:3]) # using slicing

# Creating custom labels
print("---------------------------------")
s1 = pd.Series([22, 25, 27, 29, 24], index=["John", "David", "Thomas", "Ross", "Kramer"])
print(s1)

# Indexing
print(s1["John"])
print(s1["Thomas"])
#print(s1[0]) # Can do this too, just get a warning not an error
#Generally we don't use custom labels and indexing together
print(s1.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3
0    1
1    2
2    3
dtype: int64
---------------------------------
John      22
David     25
Thomas    27
Ross      29
Kramer    24
dtype: int64
22
27
Index(['John', 'David', 'Thomas', 'Ross', 'Kramer'], dtype='object')

In [ ]:
# Series properties
s2 = pd.Series([1, 2, 3, 4, 5])
print(s2)

new_s2 = s2.drop(1)
print(s2)
print(new_s2)

#Other properties are same as in numPy arrays:

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
2    3
3    4
4    5
dtype: int64

In [27]:
# DataFrame in pandas
data = {
    "Name:": ["Thomas", "John", "Henry"],
    "Age:" : [24, 25, 27],
    "CGPA:" : [9.1, 8.9, 9.0]
}

df = pd.DataFrame(data)
print(df)
print(type(df))
print("-------------")
print(df.index)
print(df.columns)

    Name:  Age:  CGPA:
0  Thomas    24    9.1
1    John    25    8.9
2   Henry    27    9.0
<class 'pandas.core.frame.DataFrame'>
-------------
RangeIndex(start=0, stop=3, step=1)
Index(['Name:', 'Age:', 'CGPA:'], dtype='object')

In [24]:
df

    Name:  Age:  CGPA:
0  Thomas    24    9.1
1    John    25    8.9
2   Henry    27    9.0

In [31]:
# Creating dataFrame using list of lists
data1 = pd.DataFrame([["Adam", 22], ["Jack", 23], ["Tim", 25]], columns=["Name", "Age"])
print(data1)

   Name  Age
0  Adam   22
1  Jack   23
2   Tim   25

In [33]:
# Creating using numPy arrays
import numpy as np
num_arr = np.array([[1, 2, 3], [4, 5, 6]])

num_df = pd.DataFrame(num_arr, columns=["A", "B", "C" ])
print(num_df)

   A  B  C
0  1  2  3
1  4  5  6

In [35]:
# Performing some operations on csv and json files
csv_df = pd.read_csv("employee_data.csv")
print(csv_df)
print(type(csv_df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

# Performing EDA Operations

In [41]:
csv_df.head() # prints top 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [42]:
csv_df.tail() # print last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [52]:
csv_df.sample() # gives a random row from dataFrame

   ID   Name  Age Department  Salary
9  10  Julia   30    Finance   60000

In [49]:
csv_df.info() # gives info about dataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 528.0+ bytes

In [48]:
csv_df.shape # print number of rows and columns

(10, 5)

In [46]:
csv_df.columns # print column names

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [50]:
csv_df.describe() # gives statistical summary of dataFrame

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [54]:
csv_df.nunique() # gives number of unique values in each column

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [36]:
# For json files
json_df = pd.read_json("employee.json")
print(json_df)
print(type(json_df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>